name: we-chat-application

services:
  db:
    image: postgres
    container_name: we-postgres-db
    environment:
      - POSTGRES_DB=wechatdb
      - POSTGRES_USER=wechatuser
      - POSTGRES_PASSWORD=wechatpassword
    ports:
      - "5432:5432"
