# Generated by Django 5.0.4 on 2024-05-05 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_user', '0002_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_avatar',
            field=models.ImageField(blank=True, default='emil-kowalski.png', null=True, upload_to='user_avatar/'),
        ),
    ]
