# Generated by Django 5.0.4 on 2024-05-05 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_user', '0003_profile_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_avatar',
            field=models.ImageField(blank=True, default='default-avatar.png', null=True, upload_to='user_avatar/'),
        ),
    ]
